"""create_db

Revision ID: b4a75aba1ca0
Revises: 04dbe29719b9
Create Date: 2024-06-27 03:14:18.110339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4a75aba1ca0'
down_revision: Union[str, None] = '04dbe29719b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_centers',
    sa.Column('pk_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=60), nullable=False),
    sa.Column('owner', sa.String(length=30), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('pk_id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('training_center')
    op.drop_constraint('athletes_training_center_id_fkey', 'athletes', type_='foreignkey')
    op.create_foreign_key(None, 'athletes', 'training_centers', ['training_center_id'], ['pk_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'athletes', type_='foreignkey')
    op.create_foreign_key('athletes_training_center_id_fkey', 'athletes', 'training_center', ['training_center_id'], ['pk_id'])
    op.create_table('training_center',
    sa.Column('pk_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('owner', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('pk_id', name='training_center_pkey'),
    sa.UniqueConstraint('name', name='training_center_name_key')
    )
    op.drop_table('training_centers')
    # ### end Alembic commands ###
